/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_kda_kkt.py (kernel chunk_kda_scaled_dot_kkt_fwd_kernel_intra_sub_inter); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_kda_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3();
void unload_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3();

int kda_kkt_inter_get_num_algos(void);

CUresult kda_kkt_inter_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult kda_kkt_inter(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_kda_kkt_inter();
void unload_kda_kkt_inter();
