/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/kda_gate_cumsum.py (kernel kda_gate_cumsum_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/kda_gate_cumsum.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2
CUresult kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((g % 16 == 0) && (A % 16 == 0) && (y % 16 == 0) && (g_bias % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213(stream, g, A, y, g_bias, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2
void load_kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213();
void load_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2() {
  load_kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213();
}

// unload for: kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2
void unload_kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213();
void unload_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2() {
  unload_kda_gate_cumsum_dd95a106_0d1d2d3d4d5d678910111213();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t kda_gate_cumsum_kernels[] = {
  kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2,
};

int kda_gate_cumsum_get_num_algos(void){
  return (int)(sizeof(kda_gate_cumsum_kernels) / sizeof(kda_gate_cumsum_kernels[0]));
}

CUresult kda_gate_cumsum(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(kda_gate_cumsum_kernels));
  return kda_gate_cumsum_kernels[algo_id](stream, g, A, y, g_bias, cu_seqlens, chunk_indices, T, NT);
}

void load_kda_gate_cumsum(void){
  load_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2();
}

void unload_kda_gate_cumsum(void){
  unload_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2();
}


CUresult kda_gate_cumsum_default(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return kda_gate_cumsum(stream, g, A, y, g_bias, cu_seqlens, chunk_indices, T, NT, 0);
}
