/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_gla_o.py (kernel chunk_gla_fwd_kernel_o); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_gla_o.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: kda_gla_o_32x128x128x64x64x64x1_warps4xstages3
CUresult kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516(CUstream stream, CUdeviceptr q, CUdeviceptr v, CUdeviceptr g, CUdeviceptr h, CUdeviceptr o, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult kda_gla_o_32x128x128x64x64x64x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr v, CUdeviceptr g, CUdeviceptr h, CUdeviceptr o, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((q % 16 == 0) && (v % 16 == 0) && (g % 16 == 0) && (h % 16 == 0) && (o % 16 == 0) && (A % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516(stream, q, v, g, h, o, A, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: kda_gla_o_32x128x128x64x64x64x1_warps4xstages3
void load_kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516();
void load_kda_gla_o_32x128x128x64x64x64x1_warps4xstages3() {
  load_kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516();
}

// unload for: kda_gla_o_32x128x128x64x64x64x1_warps4xstages3
void unload_kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516();
void unload_kda_gla_o_32x128x128x64x64x64x1_warps4xstages3() {
  unload_kda_gla_o_9473c5e7_0d1d2d3d4d5d6d7d8910111213141516();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr v, CUdeviceptr g, CUdeviceptr h, CUdeviceptr o, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t kda_gla_o_kernels[] = {
  kda_gla_o_32x128x128x64x64x64x1_warps4xstages3,
};

int kda_gla_o_get_num_algos(void){
  return (int)(sizeof(kda_gla_o_kernels) / sizeof(kda_gla_o_kernels[0]));
}

CUresult kda_gla_o(CUstream stream, CUdeviceptr q, CUdeviceptr v, CUdeviceptr g, CUdeviceptr h, CUdeviceptr o, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(kda_gla_o_kernels));
  return kda_gla_o_kernels[algo_id](stream, q, v, g, h, o, A, cu_seqlens, chunk_indices, T, NT);
}

void load_kda_gla_o(void){
  load_kda_gla_o_32x128x128x64x64x64x1_warps4xstages3();
}

void unload_kda_gla_o(void){
  unload_kda_gla_o_32x128x128x64x64x64x1_warps4xstages3();
}


CUresult kda_gla_o_default(CUstream stream, CUdeviceptr q, CUdeviceptr v, CUdeviceptr g, CUdeviceptr h, CUdeviceptr o, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return kda_gla_o(stream, q, v, g, h, o, A, cu_seqlens, chunk_indices, T, NT, 0);
}
