/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/recompute_w_u_kda.py (kernel recompute_w_u_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/recompute_w_u_kda.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3
CUresult kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((q % 16 == 0) && (k % 16 == 0) && (qg % 16 == 0) && (kg % 16 == 0) && (v % 16 == 0) && (beta % 16 == 0) && (w % 16 == 0) && (u % 16 == 0) && (A % 16 == 0) && (gk % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122(stream, q, k, qg, kg, v, beta, w, u, A, gk, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3
void load_kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122();
void load_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3() {
  load_kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122();
}

// unload for: kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3
void unload_kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122();
void unload_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3() {
  unload_kda_wu_311de8c7_0d1d2d3d4d5d6d7d8d9d10d11d1213141516171819202122();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t kda_wu_kernels[] = {
  kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3,
};

int kda_wu_get_num_algos(void){
  return (int)(sizeof(kda_wu_kernels) / sizeof(kda_wu_kernels[0]));
}

CUresult kda_wu(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(kda_wu_kernels));
  return kda_wu_kernels[algo_id](stream, q, k, qg, kg, v, beta, w, u, A, gk, cu_seqlens, chunk_indices, T, NT);
}

void load_kda_wu(void){
  load_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3();
}

void unload_kda_wu(void){
  unload_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3();
}


CUresult kda_wu_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return kda_wu(stream, q, k, qg, kg, v, beta, w, u, A, gk, cu_seqlens, chunk_indices, T, NT, 0);
}
