/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_kda_kkt.py (kernel chunk_kda_scaled_dot_kkt_fwd_kernel_intra_sub_intra); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_kda_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: kda_kkt_intra_32x128x64x16x128x1_warps4xstages2
CUresult kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult kda_kkt_intra_32x128x64x16x128x1_warps4xstages2(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((q % 16 == 0) && (k % 16 == 0) && (g % 16 == 0) && (beta % 16 == 0) && (A % 16 == 0) && (Aqk % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415(stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: kda_kkt_intra_32x128x64x16x128x1_warps4xstages2
void load_kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415();
void load_kda_kkt_intra_32x128x64x16x128x1_warps4xstages2() {
  load_kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415();
}

// unload for: kda_kkt_intra_32x128x64x16x128x1_warps4xstages2
void unload_kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415();
void unload_kda_kkt_intra_32x128x64x16x128x1_warps4xstages2() {
  unload_kda_kkt_intra_f29ec1bd_0d1d2d3d4d5d6d7d89101112131415();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t kda_kkt_intra_kernels[] = {
  kda_kkt_intra_32x128x64x16x128x1_warps4xstages2,
};

int kda_kkt_intra_get_num_algos(void){
  return (int)(sizeof(kda_kkt_intra_kernels) / sizeof(kda_kkt_intra_kernels[0]));
}

CUresult kda_kkt_intra(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(kda_kkt_intra_kernels));
  return kda_kkt_intra_kernels[algo_id](stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT);
}

void load_kda_kkt_intra(void){
  load_kda_kkt_intra_32x128x64x16x128x1_warps4xstages2();
}

void unload_kda_kkt_intra(void){
  unload_kda_kkt_intra_32x128x64x16x128x1_warps4xstages2();
}


CUresult kda_kkt_intra_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return kda_kkt_intra(stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT, 0);
}
