/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/kda_gate_cumsum.py (kernel kda_gate_cumsum_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/kda_gate_cumsum.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2();
void unload_kda_gate_cumsum_32x128x64x64x1x1_warps4xstages2();

int kda_gate_cumsum_get_num_algos(void);

CUresult kda_gate_cumsum_default(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult kda_gate_cumsum(CUstream stream, CUdeviceptr g, CUdeviceptr A, CUdeviceptr y, CUdeviceptr g_bias, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_kda_gate_cumsum();
void unload_kda_gate_cumsum();
