#!/usr/bin/env python3
"""Emit tests/vllm/models/minimax_h3_gguf_manifest.inc from a REAL H3 GGUF.

The ComfyUI-format MiniMax-H3 GGUFs (e.g. realrebelai/MiniMax-H3_GGUFs,
`MiniMax-H3-FL2VA-Q3_K_M.gguf`) are the quantized checkpoints that actually FIT
this project's hardware. This script reads only the GGUF **header** — the tensor
names, dims, types, and the `comfy.gguf.orig_shape.*` metadata — and freezes it
into a C++ fixture, so the loader's name map and shape resolution are gated
against a real 535-tensor checkpoint without checking in (or even downloading)
the ~15 GB payload.

The header is self-delimiting and lives at the front of the file, so a range
request is enough:

    curl -sL -r 0-4194303 -o h3.head \\
      https://huggingface.co/realrebelai/MiniMax-H3_GGUFs/resolve/main/MiniMax-H3-FL2VA-Q3_K_M.gguf
    python3 scripts/gen-minimax-h3-gguf-manifest.py h3.head \\
      > tests/vllm/models/minimax_h3_gguf_manifest.inc

Self-contained: deliberately does NOT use gguf-py, so it runs anywhere the file
does (same rationale as scripts/gen-gguf-nvfp4-goldens.py).
"""

import struct
import sys

(
    UINT8, INT8, UINT16, INT16, UINT32, INT32, FLOAT32, BOOL, STRING, ARRAY,
    UINT64, INT64, FLOAT64,
) = range(13)

FMT = {
    UINT8: ("<B", 1), INT8: ("<b", 1), UINT16: ("<H", 2), INT16: ("<h", 2),
    UINT32: ("<I", 4), INT32: ("<i", 4), FLOAT32: ("<f", 4), BOOL: ("<?", 1),
    UINT64: ("<Q", 8), INT64: ("<q", 8), FLOAT64: ("<d", 8),
}

# ggml_type ids (ggml.h). Only the ones a MiniMax-H3 GGUF can carry are named;
# anything else is emitted numerically so the fixture never silently mislabels.
GGML_TYPE_NAMES = {
    0: "F32", 1: "F16", 2: "Q4_0", 3: "Q4_1", 6: "Q5_0", 7: "Q5_1", 8: "Q8_0",
    9: "Q8_1", 10: "Q2_K", 11: "Q3_K", 12: "Q4_K", 13: "Q5_K", 14: "Q6_K",
    15: "Q8_K", 30: "BF16",
}


class Reader:
    def __init__(self, fh):
        self.fh = fh

    def raw(self, n):
        data = self.fh.read(n)
        if len(data) != n:
            raise SystemExit("short read: the header is larger than the fetched prefix")
        return data

    def u32(self):
        return struct.unpack("<I", self.raw(4))[0]

    def u64(self):
        return struct.unpack("<Q", self.raw(8))[0]

    def string(self):
        return self.raw(self.u64()).decode("utf-8", "replace")

    def value(self, type_id):
        if type_id in FMT:
            fmt, size = FMT[type_id]
            return struct.unpack(fmt, self.raw(size))[0]
        if type_id == STRING:
            return self.string()
        if type_id == ARRAY:
            elem = self.u32()
            count = self.u64()
            return [self.value(elem) for _ in range(count)]
        raise SystemExit(f"unknown GGUF value type {type_id}")


def main() -> int:
    if len(sys.argv) not in (2, 3):
        raise SystemExit(f"usage: {sys.argv[0]} <gguf-or-header-prefix> [symbol-prefix]")
    path = sys.argv[1]
    # The PRUNED checkpoints (unsloth/MiniMax-H3-GGUF) are a second, structurally
    # different manifest that must be frozen alongside the unpruned one, so the
    # emitted C++ identifiers are parameterized instead of hard-coded.
    sym = sys.argv[2] if len(sys.argv) == 3 else "H3Gguf"
    with open(path, "rb") as fh:
        r = Reader(fh)
        if r.raw(4) != b"GGUF":
            raise SystemExit("not a GGUF file")
        version = r.u32()
        n_tensors = r.u64()
        n_kv = r.u64()

        kv = {}
        for _ in range(n_kv):
            key = r.string()
            kv[key] = r.value(r.u32())

        tensors = []
        for _ in range(n_tensors):
            name = r.string()
            n_dims = r.u32()
            dims = [r.u64() for _ in range(n_dims)]
            type_id = r.u32()
            r.u64()  # offset — not part of the shape contract
            tensors.append((name, dims, type_id))

    tensors.sort(key=lambda t: t[0])
    out = sys.stdout
    out.write(
        "// GENERATED by scripts/gen-minimax-h3-gguf-manifest.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The tensor manifest of a REAL ComfyUI-format MiniMax-H3 GGUF\n"
        f"// (GGUF v{version}, {n_tensors} tensors, architecture "
        f"{kv.get('general.architecture', '?')!r}, file_type "
        f"{kv.get('general.file_type', '?')}). Names, dims and ggml type ids only —\n"
        "// no weight bytes. This is what gates the loader's name map and shape\n"
        "// resolution against a real checkpoint. See .agents/specs/minimax-h3.md.\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace vllm_test {\n\n"
    )
    out.write(f"inline constexpr int64_t k{sym}TensorCount = {len(tensors)};\n")
    out.write(f"inline constexpr int64_t k{sym}Version = {version};\n")
    arch = kv.get("general.architecture", "")
    out.write(f'inline constexpr const char* k{sym}Architecture = "{arch}";\n\n')

    out.write(f"struct {sym}Tensor {{\n"
              "  const char* name;\n"
              "  int64_t dims[4];   // GGUF ne order (reversed vs torch), 0-padded\n"
              "  int32_t n_dims;\n"
              "  uint32_t ggml_type;\n"
              "  int64_t orig_shape[4];  // comfy.gguf.orig_shape.<name>, 0 if absent\n"
              "  int32_t orig_n_dims;    // 0 when the key is absent\n"
              "};\n\n")
    out.write(f"inline constexpr {sym}Tensor k{sym}Tensors[] = {{\n")
    for name, dims, type_id in tensors:
        padded = list(dims) + [0] * (4 - len(dims))
        orig = kv.get(f"comfy.gguf.orig_shape.{name}")
        if orig is None:
            orig_padded, orig_n = [0, 0, 0, 0], 0
        else:
            orig_padded = list(int(v) for v in orig) + [0] * (4 - len(orig))
            orig_n = len(orig)
        type_name = GGML_TYPE_NAMES.get(type_id, str(type_id))
        out.write(
            f'    {{"{name}", {{{", ".join(str(v) for v in padded)}}}, {len(dims)}, '
            f"{type_id}u, {{{', '.join(str(v) for v in orig_padded)}}}, {orig_n}}},"
            f"  // {type_name}\n"
        )
    out.write("};\n\n")
    out.write("}  // namespace vllm_test\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
