#!/usr/bin/env python3
"""Emit tests/vllm/models/minimax_h3_adaln_curve_goldens.inc.

The PRUNED MiniMax-H3 checkpoints (unsloth/MiniMax-H3-GGUF,
lilcheaty/MiniMax-H3-NVFP4 `*_pruned_nvfp4.safetensors`) replace the sinusoidal +
2-layer-MLP time embedder with an `adaln_t_table` buffer that is interpolated at
the per-row timestep. That refactor is defined in ComfyUI, NOT in vLLM-Omni —
vLLM-Omni has no curve form at all — so ComfyUI is the upstream anchor:

    comfy/ldm/minimax/model.py:610-615

        table = comfy.model_management.cast_to(self.adaln_t_table, device=device)
        pos = t_vals.clamp(0.0, 1.0) * (table.shape[0] - 1)
        i0 = pos.floor().long().clamp(max=table.shape[0] - 2)
        t_emb = torch.lerp(table[i0], table[i0 + 1], (pos - i0).unsqueeze(1))

ComfyUI's `MiniMaxH3Model` cannot be imported standalone (it pulls in comfy.ops,
comfy.model_management, comfy.patcher_extension), so — exactly as
gen-minimax-h3-goldens.py restates upstream's DiT at TP=1 — the four lines above
are restated here VERBATIM against torch, and the tensors they produce are frozen
as the C++ gate. The restatement is the whole algorithm: there is nothing else in
the curve path.

Weights and timesteps are rebuilt on both sides from the same FNV-1a + splitmix64
stream used by the rest of the H3 suite, so no weight byte is checked in.

Usage:
    python3 scripts/gen-minimax-h3-adaln-curve-goldens.py \
        --out tests/vllm/models/minimax_h3_adaln_curve_goldens.inc

Needs torch (CPU only).
"""

from __future__ import annotations

import argparse
import sys

import torch

# The H3 suite's shared deterministic stream (see gen-minimax-h3-goldens.py):
# FNV-1a over the tensor name, then splitmix64, mapped to [-1, 1).
_FNV_OFFSET = 0xCBF29CE484222325
_FNV_PRIME = 0x100000001B3
_MASK = (1 << 64) - 1


def _fnv1a(name: str) -> int:
    h = _FNV_OFFSET
    for byte in name.encode():
        h = ((h ^ byte) * _FNV_PRIME) & _MASK
    return h


def _splitmix64(x: int) -> int:
    x = (x + 0x9E3779B97F4A7C15) & _MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK
    return z ^ (z >> 31)


def deterministic(name: str, *shape: int) -> torch.Tensor:
    """h3_rand (gen-minimax-h3-goldens.py:75-85), same stream, same mapping."""
    n = 1
    for dim in shape:
        n *= dim
    seed = _fnv1a(name)
    values = [
        (_splitmix64((seed + i) & _MASK) >> 11) * (2.0 ** -53) * 2.0 - 1.0
        for i in range(n)
    ]
    return torch.tensor(values, dtype=torch.float32).reshape(*shape)


def adaln_curve_embed(table: torch.Tensor, t_vals: torch.Tensor) -> torch.Tensor:
    """comfy/ldm/minimax/model.py:612-615, verbatim."""
    # t in [0,1] -> fractional grid index, out-of-range t clamps to the curve ends
    pos = t_vals.clamp(0.0, 1.0) * (table.shape[0] - 1)
    # lower grid row; max-clamp keeps t=1.0 on the last interval instead of
    # reading past the table
    i0 = pos.floor().long().clamp(max=table.shape[0] - 2)
    # blend the two rows by the fractional part
    return torch.lerp(table[i0], table[i0 + 1], (pos - i0).unsqueeze(1))


def emit(out, name: str, tensor: torch.Tensor) -> None:
    flat = tensor.reshape(-1).tolist()
    out.write(f"inline constexpr int64_t k{name}Count = {len(flat)};\n")
    out.write(f"inline constexpr float k{name}[] = {{\n")
    for i in range(0, len(flat), 6):
        chunk = ", ".join(f"{v:.9e}f" for v in flat[i:i + 6])
        out.write(f"    {chunk},\n")
    out.write("};\n\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="-")
    args = ap.parse_args()
    out = sys.stdout if args.out == "-" else open(args.out, "w")

    # A reduced grid (the shipped checkpoint is [1025, 8]); the arithmetic is
    # identical and a small grid makes every interesting index reachable.
    grid, dim = 17, 8
    table = deterministic("adaln_t_table", grid, dim)

    # Every case the clamped-lerp has to get right, in one vector:
    #   exact grid points (0, 1/16, 8/16, 1), a point inside an interval, and
    #   both out-of-range clamps.
    t_vals = torch.tensor(
        [0.0, 0.0625, 0.03125, 0.5, 0.53125, 0.999, 1.0, -0.25, 1.25],
        dtype=torch.float32,
    )

    out.write(
        "// GENERATED by scripts/gen-minimax-h3-adaln-curve-goldens.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The PRUNED (curve-form) AdaLN timestep embedding, frozen from a verbatim\n"
        "// restatement of comfy/ldm/minimax/model.py:612-615. Table and timesteps are\n"
        "// rebuilt on the C++ side from the same FNV-1a + splitmix64 stream, so no weight\n"
        "// byte is checked in. See .agents/specs/minimax-h3.md section 8.20.\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace vllm_test {\n\n"
    )
    out.write(f"inline constexpr int64_t kH3AdalnCurveGrid = {grid};\n")
    out.write(f"inline constexpr int64_t kH3AdalnCurveDim = {dim};\n\n")
    emit(out, "H3AdalnCurveT", t_vals)
    emit(out, "H3AdalnCurveEmb", adaln_curve_embed(table, t_vals))
    out.write("}  // namespace vllm_test\n")
    if out is not sys.stdout:
        out.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
