/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/recompute_w_u_kda.py (kernel recompute_w_u_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/recompute_w_u_kda.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3();
void unload_kda_wu_32x128x128x64x64x64x0x1x1_warps4xstages3();

int kda_wu_get_num_algos(void);

CUresult kda_wu_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult kda_wu(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr qg, CUdeviceptr kg, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr gk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_kda_wu();
void unload_kda_wu();
